#ifndef PORT_H
// {
	#define PORT_H

	#define ANODE_SEVEN_SEGMENT_LED_PORT P2
	sbit ANODE_SEVEN_SEGMENT_LED_EN_PIN = P2^7;
	#define CATHODE_SEVEN_SEGMENT_LED_PORT P3
	sbit CATHODE_SEVEN_SEGMENT_LED_EN_PIN = P3^7;
// }
#endif