#ifndef PORT_H
#define PORT_H

sbit CONTINUE_PAUSE_BUTTON = P1^0;
sbit START_STOP_BUTTON = P1^1;

#define SEVEN_SEGMENT_LED_DATA_PORT P2
sbit SEVEN_SEGMENT_LED_CONTROL_PIN_1 = P3^1;
sbit SEVEN_SEGMENT_LED_CONTROL_PIN_0 = P3^0;

sbit GREEN_LED_PIN = P3^2;
sbit YELLOW_LED_PIN = P3^3;

#endif